#
# Oracle Linux Automation Manager
#
# Copyright (c) 2022 Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at
# https://oss.oracle.com/licenses/upl.
#
# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
#
# Description:
#
# This is the Playbook file to install OCNE rpms and the deployment of OCNE
#   - edit the hosts.ini file to configure the nodes for the cluster
#   - edit the group_vars/all.yml to configure variables for your environment
---

- name: Import Pre requisites playbook
  ansible.builtin.import_playbook: play-prerequisites.yml
  vars:
    hostlist: "ocne_op ocne_kube_control ocne_kube_worker"

- name: Import Operator playbook
  ansible.builtin.import_playbook: play-operator.yml

- name: Import Kube playbook
  ansible.builtin.import_playbook: play-k8snodes.yml
  vars:
    hostlist: "ocne_kube_control ocne_kube_worker"

- name: Import Nginx playbook
  ansible.builtin.import_playbook: play-nginxmlb.yml
  vars:
    hostlist: "ocne_kube_control"
  when:
  - ha == true

- name: Import Certificates setup playbook
  ansible.builtin.import_playbook: play-certs-setup.yml

- name: Import Certificates Restripc IPS playbook
  ansible.builtin.import_playbook: play-certs-setup-rips.yml

- name: Import API Server Start playbook
  ansible.builtin.import_playbook: play-api-server-start.yml

- name: Import Agent start playbook
  ansible.builtin.import_playbook: play-agent-start.yml
  vars:
    hostlist: "ocne_kube_control ocne_kube_worker"

- import_playbook: play-kube-reset.yml

# Create an environment
- import_playbook: play-env-create.yml

# Create Kubernetes module with self-signed Certificates and Load Balancer
- import_playbook: play-mod-kube-create.yml

- name: Import module Helm playbook
  ansible.builtin.import_playbook: play-mod-helm-create.yml
  when:
  - ocne_helm != ""

# Set up kubectl on master nodes
- name: Import Kubectl setup playbook
  ansible.builtin.import_playbook: play-kubectl.yml
  vars:
    hostlist: ocne_kube_control
