#
# Oracle Linux Automation Manager
#
# Copyright (c) 2022 Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at
# https://oss.oracle.com/licenses/upl.
#
# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
#
# Description: Ansible playbook to create
# and install the OCNE Helm and Istio modules.
#
# yamllint disable

---

- name: Create and Deploy Helm
  hosts: ocne_op
  gather_facts: false

  tasks:

  - name: Create a Helm  Module
    command: olcnectl module create \
            --environment-name {{ ocne_environment }} \
            --module helm \
            --name {{ ocne_helm }} \
            --helm-kubernetes-module {{ ocne_k8s }}

  - name: Validate the Helm Module
    command: olcnectl module validate \
            --environment-name {{ ocne_environment }} \
            --name {{ ocne_helm }} 

  - name: Deploy the Helm Module
    command: olcnectl module install \
            --environment-name {{ ocne_environment }} \
            --name {{ ocne_helm }}
