#
# Oracle Linux Automation Manager
#
# Copyright (c) 2022 Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at
# https://oss.oracle.com/licenses/upl.
#
# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
#
# Description:
#

---

- name: Add New Master and Worker Nodes to the Cluster
  hosts: ocne_op
  gather_facts: false

  tasks:

  - name: Pause to give system time to install
    command: sleep 5m

  - name: Add master and worker nodes to a Kubernetes module
    command: olcnectl module update \
           --environment-name {{ ocne_environment }} \
           --name {{ ocne_k8s }} \
           --master-nodes {{ control_nodes }},{{ add_control_nodes }} \
           --worker-nodes {{ worker_nodes }},{{ add_worker_nodes }} \
           --force
    register: add_kubenodes
    until: add_kubenodes is not failed
    retries: 3
