#
# Oracle Linux Automation Manager
#
# Copyright (c) 2022 Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at
# https://oss.oracle.com/licenses/upl.
#
# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
#

---

- name: Set up OCNE Agent with the Certificates
  hosts: "{{hostlist}}"
  gather_facts: false
  become: yes
  become_method: sudo

  tasks:

  - name: Start OCNE Agent with the Certificates
    shell: |
           /etc/olcne/bootstrap-olcne.sh \
           --secret-manager-type file \
           --olcne-node-cert-path /etc/olcne/configs/certificates/production/node.cert \
           --olcne-ca-path /etc/olcne/configs/certificates/production/ca.cert \
           --olcne-node-key-path /etc/olcne/configs/certificates/production/node.key \
           --olcne-component agent
