#
# Oracle Linux Automation Manager
#
# Copyright (c) 2022 Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at
# https://oss.oracle.com/licenses/upl.
#
# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
#
# Description:
#
# This is the Playbook file to uninstall OCNE RPMs, files and directories from the nodes
#   - use after you have run undeploy-ocne.yml file

---

- name: Clean up and Remove an OCNE RPMs
  hosts: all
  gather_facts: false
  become: yes
  become_method: sudo

  tasks:

  - name: Remove OCNE RPMs
    ansible.builtin.dnf:
      name: 
        - kubeadm 
        - kubectl 
        - kubelet 
        - olcnectl 
        - olcne-api-server 
        - olcne-utils 
        - olcne-agent 
        - crio 
        - cri-tools 
        - olcne-nginx 
        - keepalived 
        - istio 
        - olcne-istio-chart 
        - helm 
        - conmon 
        - kata-image 
        - kata-runtime 
        - kernel-uek-container 
        - nginx 
        - etcd 
        - olcne-prometheus-chart 
        - olcne-selinux 
        - runc
      state: absent
    ignore_errors: yes

  - name: Remove /etc/olcne directory
    file:
      path: /etc/olcne
      state: absent

  - name: Remove /var/olcne directory
    file:
      path: /var/olcne
      state: absent

  - name: Remove /root/.olcne directory
    file:
      path: /root/.olcne
      state: absent
