#
# Oracle Linux Automation Manager
#
# Copyright (c) 2022 Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at
# https://oss.oracle.com/licenses/upl.
#
# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
#
# Description: Ansible playbook to deploy the online uptrack client
# Prerequisites:
#     - server must be registered in ULN
#     - olX_x86_64_ksplice must be added to subscribed ULN channels,
#       where X is 7,8 or 9
#
# yamllint disable
---

- name: Deploy Ksplice uptrack online client
  hosts: all
  become: yes
  become_method: sudo
  gather_facts: yes

  vars:
    install_on_reboot: "yes"
    upgrade_on_reboot: "yes"
    autoinstall: "yes"
    https_proxy: "None"
    first_update: true

  tasks:

  - name: Make sure ksplice offline packages are removed
    package: name=ksplice-tools,uptrack-offline state=absent

  - name: Install ksplice uptrack offline package
    package: name=uptrack state=present

  - name: Adjust install_on_reboot in uptrack.conf configuration file
    ini_file:
      dest: /etc/uptrack/uptrack.conf
      section: Settings
      option: install_on_reboot
      value: "{{ install_on_reboot }}"

  - name: Adjust upgrade_on_reboot in uptrack.conf configuration file
    ini_file:
      dest: /etc/uptrack/uptrack.conf
      section: Settings
      option: upgrade_on_reboot
      value: "{{ upgrade_on_reboot }}"

  - name: Adjust autoinstall in uptrack.conf configuration file
    ini_file:
      dest: /etc/uptrack/uptrack.conf
      section: Settings
      option: autoinstall
      value: "{{ autoinstall }}"

  - name: Adjust https_proxy in uptrack.conf configuration file
    ini_file:
      dest: /etc/uptrack/uptrack.conf
      section: Network
      option: https_proxy
      value: "{{ https_proxy }}"

  - name: Update to latest Ksplice uptrack updates
    ansible.builtin.command: /usr/sbin/uptrack-upgrade --all -y
    when: first_update == true
  
