# Copyright (c) 2022 Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at
# https://oss.oracle.com/licenses/upl.
#
# Description: Playbook to add a user with password to the targeted host.
#
# Options:
#   enable_sudo: Adds the new user to the wheel group to allow sudo access.
#   enable_passwordless_sudo: Adds file to /etc/sudoers.d allowing passwordless sudo access.
#
# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.

---
- hosts: all
  becomes: yes

  vars:
    username: oracle
    user_default_password: oracle
    enable_sudo: false
    enable_passwordless_sudo: false

  tasks:

    - name: add user account with access to sudo
      user:
        name: "{{ username }}"
        password: "{{ user_default_password | password_hash('sha512') }}"
        comment: Ansible created user
        groups: wheel
        append: yes
        update_password: on_create

    - name: set authorized key for user using local pubilc key file
      authorized_key:
        user: "{{ username }}"
        state: present
        key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/{{ ssh_keyfile }}') }}"

    - name: set user with passwordless sudo access
      lineinfile:
        path: /etc/sudoers.d/oracle
        regexp: '{{ username }} ALL='
        line: '{{ username }} ALL=(ALL:ALL) NOPASSWD: ALL'
        state: present
        create: yes

