
---
- name: oVirt infra
  hosts: localhost
  connection: local
  gather_facts: false



  vars:
    engine_fqdn: "{{ lookup('env', 'OVIRT_URL') }}"
    engine_user: "{{ lookup('env', 'OVIRT_USERNAME') }}"
    engine_password: "{{ lookup('env', 'OVIRT_PASSWORD') }}"
    engine_cafile: /etc/pki/ovirt-engine/ca.pem

    debug_vm_create: true
    db_vm:
      state: running
      cluster: "{{ cluster_name }}"
      template: "{{ template_name }}"
      memory: 1GiB
      memory_max: 2GiB
      cores: 1
      tag:
        - db
        - dbvm
      disks:
        - size: 1GiB
          name: data
          storage_domain: "{{ storage_domain}}"
          interface: virtio

    vms:
      - name: postgresql-vm-0
        memory: 2GiB
        cloud_init:
          host_name: ps.example.com
          root_password: 'mypassword'
          authorized_ssh_keys: ssh-rsa A...LGx ondra@ondra
        profile: "{{ db_vm }}"
        tag:
          - pgsql
          - httpd

  roles:
    - vm_infra
  collections:
    - ovirt.ovirt
